# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: compiledb
        name: compiledb
        entry: compiledb
        language: system
        args: [--overwrite, -v, make, -f, test/Makefile, -n]
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-executables-have-shebangs # Ensures that (non-binary) executables have a shebang.
      - id: check-json # This hook checks json files for parseable syntax.
      - id: check-yaml # This hook checks yaml files for parseable syntax.
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
      - id: pretty-format-json # This hook sets a standard for formatting JSON files.
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
        exclude: compile_commands.json
      - id: trailing-whitespace # This hook trims trailing whitespace.
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: clang-format
        args: [--style=file, -i]
      - id: clang-tidy
        args: [-checks=clang-diagnostic-return-type]
      - id: cppcheck
        args:
          [
            --quiet,
            --enable=all,
            --suppress=unusedFunction,
            --suppress=unmatchedSuppression,
            --suppress=missingInclude,
            --suppress=ConfigurationNotChecked,
          ]
