name: main-ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noahp/nocli:2023-01-06
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      # this should not be necessary! but git doesn't work without it
      - name: Set git safe directory
        run: |
          git config --global --add safe.directory "${PWD}"

      - name: ci.sh
        run: |
          ./ci.sh
